# directories:
# directories:
mirror_module_path: True
window:
  position_string: OO
  monitor_index: 1
  # position_string: UR
  # size: (1800, 1125)
  # position: (0,-1169)
  full_screen: True

camera:
  resolution: (3024, 1964)
  background_color: "#000000"
  fps: 60
  background_opacity: 1.0
file_writer:
  saturation: 1.5
text:
  font: "CMU Serif"
  alignment: "CENTER"
tex:
  template: "default"
embed:
  autoreload: false
  ignore_manimlib_modules_on_reload: true
