set allow-duplicate-variables := true

# set working-directory := "./../../../"

slides := "FirstTitle WhatIsNewtons WhatIsOilersMethod"

default: playground

playground scene="Playground":
    @echo $(pwd)
    @uv run manimgl "{{ justfile_dir() }}/playground.py" {{ scene }}

@gl file="Slides.py" scene="":
    @uv run manimgl "{{ justfile_dir() }}/{{ file }}" {{ scene }}

@render:
    @uv run manim-slides render --GL {{ justfile_dir() }}/Slides.py {{ slides }}

@present:
    @uv run manim-slides present {{ slides }}
