set allow-duplicate-variables := true

# set working-directory := "./../../../"

slides := "FirstTitle WhatIsNewtons NewtonCubic FixedPointMethod"

default: playground

playground scene="Playground":
    @echo $(pwd)
    @uv run manimgl "{{ justfile_dir() }}/playground.py" {{ scene }}

@gl file="Slides.py" scene="":
    @uv run manimgl "{{ justfile_dir() }}/{{ file }}" {{ scene }}

@render slides=slides:
    @uv run manim-slides render --GL {{ justfile_dir() }}/Slides.py {{ slides }}

@renderm slides=slides:
    @uv run manim-slides render --GL {{ justfile_dir() }}/Slides.py {{ slides }} -m

@renderl slides=slides:
    @uv run manim-slides render --GL {{ justfile_dir() }}/Slides.py {{ slides }} -l

@present:
    @uv run manim-slides present {{ slides }}
