set allow-duplicate-variables := true
set working-directory := "./../../../"

slides := "FirstTitle WhatIsNewtons WhatIsOilersMethod"

default: playground

playground scene="Playground": (gl scene "./playground.py")

gl scene="" file="./Slides.py":
    uv run manimgl {{ justfile_dir() }}/{{ file }} {{ scene }}

render:
    uv run manim-slides render --GL {{ justfile_dir() }}/Slides.py {{ slides }}

present:
    uv run manim-slides present {{ slides }}
