set allow-duplicate-variables := true
set allow-duplicate-recipes := true
set working-directory := "../../../"

import "../../../Justfile"

project := "mat557/interp/Spline.py"
scenes := "RotPara"
renderer := "cairo"

@preview scenes=scenes:
    echo $(pwd)
    echo Rendering {{ project }}
    @uv run manim render \
    --dry_run -p \
     "{{ PROJECTS_DIR }}/projects/{{ project }}" \
     {{ scenes }}
    # --renderer=opengl \
